### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by LeSnake04** [bevy-jam-team/unfair-boss-chaos#3]
We should test

# Linux
## EndeavourOS (LeSnake)
- [x] Firefox fresh profile
- [x] Firefox Hardened profile
- [ ] Chromium – Crahes after a  few seconds with error code SIGIL
- [ ] Brave  – Crashes when spamming bullets – Code SIGIL

# Windows
- [ ] Firefox
- [ ] Brave
- [ ] Chrome
- [ ] Edge

# MacOS
_(does anyone of us has a mac, a hackintosh or lives with someone with a mac?)_
- [ ] Safari
- [ ] Brave
- [ ] Firefox
- [ ] Chrome

**Comment by MyIsaak** [comment]
closing this because normally wasm build work on all modern browsers. check caniuse.com
